# Generated by Django 4.0.6 on 2022-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('issue', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
